version: '3.2'

networks:
    elk:
      driver: bridge

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/log:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
        - esdata1:/usr/share/elasticsearch/data
        - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9000
    networks:
        - elk

  kibana:
      image: docker.elastic.co/kibana/kibana:7.5.0
      container_name: kibana
      environment:
          ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ports:
          - 5601:5601
      depends_on:
          - elasticsearch
      networks:
          - elk

  filebeat:
      image: docker.elastic.co/beats/filebeat:7.5.0
      container_name: filebeat
      volumes:
          - ./filebeat/modules.d:/usr/share/filebeat/modules.d
          - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
          - ./nginx/log:/var/log/nginx
      environment:
          - "TZ=Europe/Paris"
      depends_on:
          - nginx
          - elasticsearch
          - kibana
      networks:
          - elk
volumes:
    esdata1:
      driver: local
