version: '3'

networks:

    atlas-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.32.0.0/16
services:

    atlas-nginx:
        image: nginx:latest
        container_name: atlas-nginx
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        networks:
            atlas-network:
                ipv4_address: 172.32.0.10
        ports:
            - "12880:80"

    atlas-elasticsearch:
        image: elasticsearch:7.5.0
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        container_name: atlas-elasticsearch
        networks:
            atlas-network:
                ipv4_address: 172.32.0.20
        ports:
            - "2811:9200"
            - "2911:9300"

    atlas-kibana:
        image: kibana:7.5.0
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://atlas-elasticsearch:9200
        container_name: atlas-kibana
        networks:
            atlas-network:
                ipv4_address: 172.32.0.30
        ports:
            - "5555:5601"

    atlas-filebeat:
        image: docker.elastic.co/beats/filebeat:7.6.1
        container_name: atlas-filebeat
        volumes:
            - "./filebeat/modules.d:/usr/share/filebeat/modules.d"
            - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
            - "./filebeat/filebeat_data_registry:/usr/share/filebeat/data/registry/filebeat"
            - "./nginx/log:/var/log/nginx"
        environment:
            - "TZ=Europe/Paris"
            #- ELASTICSEARCH_HOST="${ELK_HOST}:9200"
            #- KIBANA_HOST="${ELK_HOST}:5601"
        networks:
            atlas-network:
                ipv4_address: 172.32.0.40
